import { app, BrowserWindow, ipcMain, dialog, protocol } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { scanDirectoryHandler, analyzeImageHandler, generateCSV, parseCSV } from './library';

// Disable security warnings in development mode (e.g. CSP unsafe-eval from Webpack)
if (!app.isPackaged) {
  process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true';
}

const frontendBuildPath = path.join(app.getAppPath(), 'frontend-build');

// Make app:// protocol privileged before app is ready
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      allowServiceWorkers: true,
      supportFetchAPI: true,
      corsEnabled: true,
      stream: true,
    }
  },
  {
    scheme: 'local-file',
    privileges: {
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
      stream: true,
    }
  }
]);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Always load the static export files using our custom app:// protocol
  mainWindow.loadURL('app://-/index.html').catch((err) => {
    console.error("Failed to load app:// protocol:", err);
  });

  // Open the DevTools automatically in dev
  // if (!app.isPackaged) {
  //   mainWindow.webContents.openDevTools();
  // }
};

// This method will be called when Electron has finished
app.on('ready', () => {
  protocol.registerFileProtocol('local-file', (request, callback) => {
    const urlStr = request.url.replace(/^local-file:\/\//, '');
    try {
      return callback({ path: path.normalize(decodeURIComponent(urlStr)) });
    }
    catch (error) {
      console.error('Error in local-file:', error);
      return callback({ error: -2 }); // FAILED
    }
  });

  protocol.registerFileProtocol('app', (request, callback) => {
    let urlPart = request.url.substring(6); // remove 'app://'
    if (urlPart.startsWith('-/')) urlPart = urlPart.substring(2);
    if (urlPart === '-' || urlPart === '') urlPart = 'index.html';

    urlPart = decodeURIComponent(urlPart);
    // Normalize path to fix Windows leading slash issues (e.g. /_next/static)
    if (urlPart.startsWith('/')) urlPart = urlPart.substring(1);

    const filePath = path.join(frontendBuildPath, urlPart);
    console.log(`[APP-PROTOCOL] Request: ${request.url}`);
    console.log(`[APP-PROTOCOL] Resolved Path: ${filePath}`);

    try {
      // 1. Try the exact file path
      if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
        const finalPath = path.normalize(filePath);
        return callback({ path: finalPath });
      }

      // 2. Try appending .html (Next.js statically exported pages like /settings or /gallery)
      if (fs.existsSync(filePath + '.html')) {
        const finalPath = path.normalize(filePath + '.html');
        return callback({ path: finalPath });
      }

      // 3. Try index.html inside a directory
      if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
        const indexFilePath = path.join(filePath, 'index.html');
        if (fs.existsSync(indexFilePath)) {
          const finalPath = path.normalize(indexFilePath);
          return callback({ path: finalPath });
        }
      }

      // 4. Fallback for Next.js routing (404s or client side catch-all)
      const finalPath = path.normalize(path.join(frontendBuildPath, 'index.html'));
      return callback({ path: finalPath });
    } catch (e) {
      console.error("[APP-PROTOCOL] Error", e);
      return callback({ error: -6 }); // net::ERR_FILE_NOT_FOUND
    }
  });

  setupIpcHandlers();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// We will use a simple JSON file for settings to avoid ESM module issues with electron-store in CommonJS
const settingsPath = path.join(app.getPath('userData'), 'settings.json');

function getSettings() {
  try {
    if (fs.existsSync(settingsPath)) {
      const data = fs.readFileSync(settingsPath, 'utf-8');
      return JSON.parse(data);
    }
  } catch (err) {
    console.error('Error reading settings:', err);
  }
  return {};
}

function saveSettings(settings: any) {
  try {
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    return true;
  } catch (err) {
    console.error('Error saving settings:', err);
    return false;
  }
}

// IPC Handlers Setup
function setupIpcHandlers() {
  ipcMain.handle('ping', () => 'pong');

  ipcMain.handle('select-directory', async () => {
    const result = await dialog.showOpenDialog({
      properties: ['openDirectory'],
    });
    if (!result.canceled && result.filePaths.length > 0) {
      return result.filePaths[0];
    }
    return null;
  });

  ipcMain.handle('read-image', async (event, filePath) => {
    try {
      if (fs.existsSync(filePath)) {
        const fileBuffer = fs.readFileSync(filePath);
        const ext = path.extname(filePath).toLowerCase();
        let mimeType = 'image/jpeg';
        if (ext === '.png') mimeType = 'image/png';
        if (ext === '.gif') mimeType = 'image/gif';
        if (ext === '.webp') mimeType = 'image/webp';

        return {
          success: true,
          data: `data:${mimeType};base64,${fileBuffer.toString('base64')}`
        };
      }
      return { success: false, error: 'File not found' };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  });

  ipcMain.handle('get-settings', () => {
    return getSettings();
  });

  ipcMain.handle('save-settings', (event, settings) => {
    return saveSettings(settings);
  });

  ipcMain.handle('get-scanned-directories', () => {
    const settings = getSettings();
    return { success: true, directories: settings.scannedDirectories || [] };
  });

  ipcMain.handle('save-scanned-directory', (event, dirPath) => {
    const settings = getSettings();
    const dirs = settings.scannedDirectories || [];
    if (!dirs.includes(dirPath)) {
      dirs.push(dirPath);
      settings.scannedDirectories = dirs;
      saveSettings(settings);
    }
    return { success: true };
  });

  ipcMain.handle('scan-directory', async (event, dirPath) => {
    return await scanDirectoryHandler(dirPath);
  });

  ipcMain.handle('save-csv', async (event, filePath, data) => {
    try {
      const csvContent = generateCSV(data);
      fs.writeFileSync(filePath, csvContent, 'utf-8');
      return { success: true };
    } catch (error: any) {
      console.error("Save CSV error:", error);
      return { success: false, error: "Error al guardar el archivo CSV: " + error.message };
    }
  });

  ipcMain.handle('load-csv', async (event, filePath) => {
    try {
      if (!fs.existsSync(filePath)) {
        return { success: false, error: "Archivo CSV no encontrado." };
      }
      const csvContent = fs.readFileSync(filePath, 'utf-8');
      const data = await parseCSV(csvContent);
      return { success: true, data };
    } catch (error: any) {
      console.error("Load CSV error:", error);
      return { success: false, error: "Error al leer el archivo CSV: " + error.message };
    }
  });

  ipcMain.handle('analyze-image', async (event, filePath, customPrompt) => {
    try {
      if (!fs.existsSync(filePath)) {
        return { success: false, error: "Archivo no encontrado" };
      }

      const fileBuffer = fs.readFileSync(filePath);
      const base64 = fileBuffer.toString('base64');
      const mimeType = filePath.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';

      const settings = getSettings();
      const apiKey = settings.googleApiKey;

      return await analyzeImageHandler(base64, mimeType, customPrompt, apiKey);
    } catch (error: any) {
      console.error("Analyze error:", error);
      return { success: false, error: "Error al analizar la imagen: " + error.message };
    }
  });
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

